

name: update-master-from-migration

on: 
  pull_request:
    branches: [ "feature/lightspeed-transition" ]
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        if: github.ref == 'refs/heads/master'
        uses: "pascalgn/automerge-action@v0.15.3"
        
        
 #      env:
  #      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
